### PR TITLE
Login

### PR DESCRIPTION
**Pull request by xil324**
Hey Team. I've added sign up/ log in/ sign out functionalities. I will add more logic to some of them but I'd like to get some feedbacks. Thanks!

### CODE REVIEW

**Review by Jplier — COMMENTED** [review]
Looks good! nice job! Might have some conflicts in App because there are a lot of changes from other pull requests.

**Review by dmcin003 — COMMENTED** [review]
firebase logic looks good to me. Just remember to send both the uid and token to the server on the authenticate api call. Looks good to merge from my end.

**Comment by xil324** [comment]
Hey team,

A few updates: 
1. send both uid and id token to the back-end for verification
2. added logic to render buttons conditionally
3. reset the form after submission
4. add success and error messages

**Comment by lewispjjpb** [comment]
Pre-merge App.js functionality

**Pull request closed without merging**
